version: '3.5'
services:
  postgres-db:
    container_name: postgres
    image: postgres
    volumes:
      - ~/.postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - 5432:5432
    networks:
      - pgnetwork
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge